sudo: required
language: cpp

# Specify the operating system(s) to use. Here we use Ubuntu.
os:
  - linux

# You can specify different distributions
dist: xenial  # You can use 'bionic' for Ubuntu 18.04 LTS

addons:
  apt:
    # List of packages to be installed which are required for the build
    packages:
      - g++
      - make
      - libomp-dev

before_install:
  # Update system repositories and install Boost
  - sudo apt-get update
  - sudo apt-get install libboost-all-dev  # This installs Boost via apt-get if suitable
  - sudo apt-get install python3 python3-pip python3-venv

# Define the script to run for building your project
script:
  - echo "Installing Python deps"
  - pip3 install -r scripts/requirements.txt
  - echo "Building binaries for tests (pr, pr_sim)"
  - make bench/bin/pr bench/bin_sim/pr -j2 RABBIT_ENABLE=0
  - echo "Running pytest (scripts/test)"
  - pytest scripts/test -q

# Optionally define after successful build actions
after_success:
  - echo "Build successful!"

# Cache settings to speed up build process
cache:
  directories:
    - $HOME/.cache

# Notify me by email when the build status changes
notifications:
  email:
    recipients:
    - atmughrabi@gmail.com
    - atmughra@alumni.ncsu.edu
    - atmughra@virginia.edu
    on_success: change  # default: change
    on_failure: always  # default: always

branches:
  only:
    - main